.PHONY: all clean run pack build-pre build-post

all: build-pre run build-post

build-pre:

build-post:

run:
	@./run_all.sh

pack:
	zip -r run_test_lin.zip _test/ Makefile.checker \
	run_all.sh README

clean:
	rm -f *~
