- name: Install helper packages (driver-level)
  apt:
    name: ['virtualbox-guest-dkms', 'open-vm-tools', 'acl']
    state: present
    update_cache: yes

- name: Upgrade all the packages
  apt:
    upgrade: yes
    autoclean: yes
