#
# SO, 2011
# Lab #1, Introduction
#
# Task #3-karma, Linux
#
# Having fun with link-time & run-time
# Makefile

CC = gcc
CFLAGS = -Wall -g

all: main

main: main.o str.o

main.o: main.c
str.o: str.c

clean:
	rm -rf *.o main


